# Generated by Django 5.0.3 on 2024-03-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='no_of_workers',
        ),
        migrations.AddField(
            model_name='work',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='work_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='workstatus',
            field=models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_level', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('phones', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('availability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_workers_required', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers_app.role')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers_app.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='roles_required',
            field=models.ManyToManyField(default=0, through='workers_app.WorkRoleRequirement', to='workers_app.role'),
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
