# Generated by Django 5.0.3 on 2024-03-31 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_app', '0002_remove_work_no_of_workers_work_priority_work_work_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='workstatus',
            field=models.CharField(choices=[('0%', '0%'), ('100%', '100%')], default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField(default=0)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers_app.work')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers_app.worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='hours_worked',
            field=models.ManyToManyField(through='workers_app.Assignment', to='workers_app.work'),
        ),
    ]
