# Generated by Django 5.0.14 on 2025-06-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers_app", "0003_alter_work_workstatus_assignment_worker_hours_worked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="hours_worked",
        ),
        migrations.AddField(
            model_name="worker",
            name="assigned_works",
            field=models.ManyToManyField(
                related_name="assigned_workers",
                through="workers_app.Assignment",
                to="workers_app.work",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="workers_app.work",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="phones",
            field=models.CharField(max_length=15),
        ),
    ]
